### ISSUE TITLE
Not compatible with Gradle 2.0

### ISSUE THREAD

**Issue by nicklascarnegie** [janisz/gradle-wsdl2java#1]
Running the wsdl2java task using the latest Gradle 2.0 build yields the following exception (partial):

```
Caused by: java.lang.IllegalStateException: Cannot call TaskOutputs.dir(Object) on task ':xxx:wsdl2java' after task has started execution.
    at org.gradle.api.internal.tasks.TaskMutator.mutate(TaskMutator.java:35)
    at org.gradle.api.internal.tasks.DefaultTaskOutputs.dir(DefaultTaskOutputs.java:90)
    at org.gradle.api.tasks.TaskOutputs$dir$0.call(Unknown Source)
    at com.github.janisz.wsdl2java.Wsdl2JavaTask.exec(Wsdl2JavaTask.groovy:22)
    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:570)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:553)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
    ... 44 more
```

and I believe it is due to this recent change in Gradle http://www.gradle.org/docs/current/release-notes#tasks-cannot-be-changed-after-task-has-started-execution

**Comment by janisz** [comment]
Good catch. I abandoned project because I can't find a way to support multiple WSDLs. I hope I manage some time next week to handle this issues. For now I can recommend you to use [this file](https://gist.github.com/janisz/96e3bcb07c8d6f3d5ae5) I tested it and it's working with Gradle 2.0

**Comment by nicklascarnegie** [comment]
Thanks. Indeed it worked with Gradle 2.0 :)
